import AppKit
import Testing
@testable import ElegantClipbar

@Suite("Clipboard capture and restoration", .serialized)
struct ClipboardMonitorTests {
    @MainActor
    private func withPasteboard(_ body: (NSPasteboard) throws -> Void) rethrows {
        let board = NSPasteboard(name: NSPasteboard.Name("ElegantClipbar.tests.\(UUID().uuidString)"))
        defer { board.releaseGlobally() }
        try body(board)
    }

    @MainActor
    private func put(_ values: [[NSPasteboard.PasteboardType: Data]], on board: NSPasteboard) {
        let items = values.map { values in
            let item = NSPasteboardItem()
            for (type, data) in values { item.setData(data, forType: type) }
            return item
        }
        board.clearContents()
        #expect(board.writeObjects(items))
    }

    @Test
    func testExistingClipboardIsNotCapturedAtLaunch() async {
        await MainActor.run {
            withPasteboard { board in
                put([[.string: Data("existing".utf8)]], on: board)
                var captured = 0
                let monitor = ClipboardMonitor(pasteboard: board) { _, _ in captured += 1 }
                monitor.poll()
                #expect(captured == 0)
                put([[.string: Data("new".utf8)]], on: board)
                monitor.poll()
                monitor.poll()
                #expect(captured == 1)
            }
        }
    }

    @Test
    func testRichFormatsPreserveRepresentationsAndItemBoundaries() async throws {
        try await MainActor.run {
            try withPasteboard { board in
                var payload: ClipboardPayload?
                let source = ClipboardSource(name: "Test Editor", bundleIdentifier: "test.editor")
                var capturedSource: ClipboardSource?
                let monitor = ClipboardMonitor(pasteboard: board, sourceProvider: { source }) {
                    payload = $0
                    capturedSource = $1
                }
                let rich: [NSPasteboard.PasteboardType: Data] = [
                    .string: Data("Hello".utf8),
                    .html: Data("<b>Hello</b>".utf8),
                    .rtf: Data("{\\rtf1\\ansi Hello}".utf8)
                ]
                put([rich, [.string: Data("second item".utf8)]], on: board)
                monitor.poll()
                let captured = try #require(payload)
                #expect(captured.kind == .richText)
                #expect(captured.items.count == 2)
                for (type, data) in rich {
                    #expect(captured.items[0].representations[type.rawValue] == data)
                }
                let companionTypes: Set<String> = ["public.utf16-plain-text", "public.utf16-external-plain-text"]
                let extraTypes = Set(captured.items[0].representations.keys).subtracting(rich.keys.map(\.rawValue))
                #expect(extraTypes.isSubset(of: companionTypes))
                for type in extraTypes {
                    let data = try #require(captured.items[0].representations[type])
                    #expect(String(data: data, encoding: .utf16) == "Hello")
                }
                #expect(captured.items[1].representations[NSPasteboard.PasteboardType.string.rawValue] == Data("second item".utf8))
                #expect(captured.plainText == "Hello\nsecond item")
                #expect(capturedSource?.bundleIdentifier == "test.editor")
            }
        }
    }

    @Test
    func testHTMLOnlyProvidesSearchTextWithoutChangingHTML() async throws {
        try await MainActor.run {
            try withPasteboard { board in
                var payload: ClipboardPayload?
                let monitor = ClipboardMonitor(pasteboard: board) { payload = $0; _ = $1 }
                let html = Data("<p>Hello &amp; welcome</p><script>hidden()</script><p>world</p>".utf8)
                put([[.html: html]], on: board)
                monitor.poll()
                let captured = try #require(payload)
                #expect(captured.kind == .richText)
                #expect(captured.plainText.contains("Hello & welcome"))
                #expect(captured.plainText.contains("world"))
                #expect(!captured.plainText.contains("hidden()"))
                #expect(captured.items[0].representations[NSPasteboard.PasteboardType.html.rawValue] == html)
            }
        }
    }

    @Test
    func testSensitiveMarkerOnAnyItemSuppressesEntireCapture() async {
        await MainActor.run {
            withPasteboard { board in
                var captured = 0
                let monitor = ClipboardMonitor(pasteboard: board) { _, _ in captured += 1 }
                let markers = ["org.nspasteboard.ConcealedType", "org.nspasteboard.TransientType",
                               "org.nspasteboard.AutoGeneratedType", "com.agilebits.onepassword"]
                for marker in markers {
                    put([[.string: Data("private".utf8)], [NSPasteboard.PasteboardType(marker): Data([1])]], on: board)
                    monitor.poll()
                }
                #expect(captured == 0)
            }
        }
    }

    @Test
    func testPausedAndExcludedCopiesAreDropped() async {
        await MainActor.run {
            withPasteboard { board in
                var captured = 0
                let monitor = ClipboardMonitor(pasteboard: board, sourceProvider: {
                    ClipboardSource(name: "Excluded", bundleIdentifier: "test.excluded")
                }) { _, _ in captured += 1 }
                monitor.isPaused = true
                put([[.string: Data("paused".utf8)]], on: board)
                monitor.poll()
                monitor.isPaused = false
                monitor.poll()
                monitor.excludedBundleIdentifiers = ["test.excluded"]
                put([[.string: Data("excluded".utf8)]], on: board)
                monitor.poll()
                monitor.excludedBundleIdentifiers = []
                monitor.poll()
                #expect(captured == 0)
                put([[.string: Data("allowed".utf8)]], on: board)
                monitor.poll()
                #expect(captured == 1)
            }
        }
    }

    @Test
    func testRestoringPayloadPreservesRichFormatsAndDoesNotRecapture() async throws {
        try await MainActor.run {
            try withPasteboard { board in
                var captured = 0
                let monitor = ClipboardMonitor(pasteboard: board) { _, _ in captured += 1 }
                let representations = [NSPasteboard.PasteboardType.string.rawValue: Data("hello".utf8),
                                       NSPasteboard.PasteboardType.html.rawValue: Data("<b>hello</b>".utf8)]
                let payload = ClipboardPayload(items: [ClipboardPayloadItem(representations: representations),
                                                      ClipboardPayloadItem(representations: [NSPasteboard.PasteboardType.string.rawValue: Data("next".utf8)])],
                                               plainText: "hello\nnext", kind: .richText)
                try PasteService(pasteboard: board).write(payload)
                monitor.ignoreCurrentChange()
                monitor.poll()
                #expect(captured == 0)
                #expect(board.pasteboardItems?.count == 2)
                #expect(board.pasteboardItems?.first?.data(forType: .html) == representations[NSPasteboard.PasteboardType.html.rawValue])
                #expect(board.pasteboardItems?.last?.string(forType: .string) == "next")
            }
        }
    }

    @Test
    func testResumeDiscardsPausedCopyBeforeNextPoll() async {
        await MainActor.run {
            withPasteboard { board in
                var captured = 0
                let monitor = ClipboardMonitor(pasteboard: board) { _, _ in captured += 1 }
                monitor.isPaused = true
                put([[.string: Data("copied while paused".utf8)]], on: board)
                monitor.isPaused = false
                monitor.poll()
                #expect(captured == 0)
                put([[.string: Data("copied after resuming".utf8)]], on: board)
                monitor.poll()
                #expect(captured == 1)
            }
        }
    }

    @Test
    func testDepartingApplicationRemainsSourceAfterFocusChanges() async throws {
        try await MainActor.run {
            try withPasteboard { board in
                let departed = ClipboardSource(name: "Previous Editor", bundleIdentifier: "test.previous")
                let current = ClipboardSource(name: "Current Editor", bundleIdentifier: "test.current")
                var capturedSource: ClipboardSource?
                let monitor = ClipboardMonitor(pasteboard: board, sourceProvider: { current }) { _, source in
                    capturedSource = source
                }
                put([[.string: Data("copied before switching".utf8)]], on: board)
                monitor.poll(sourceOverride: departed)
                let captured = try #require(capturedSource)
                #expect(captured == departed)
            }
        }
    }

    @Test
    func testExcludedDepartingApplicationCannotLeakIntoNextApplication() async {
        await MainActor.run {
            withPasteboard { board in
                let excluded = ClipboardSource(name: "Excluded Editor", bundleIdentifier: "test.excluded")
                let current = ClipboardSource(name: "Current Editor", bundleIdentifier: "test.current")
                var captured = 0
                let monitor = ClipboardMonitor(pasteboard: board, sourceProvider: { current }) { _, _ in captured += 1 }
                monitor.excludedBundleIdentifiers = ["test.excluded"]
                put([[.string: Data("excluded copy".utf8)]], on: board)
                monitor.poll(sourceOverride: excluded)
                monitor.poll()
                #expect(captured == 0)
                put([[.string: Data("current app copy".utf8)]], on: board)
                monitor.poll()
                #expect(captured == 1)
            }
        }
    }

    @Test
    func testFilesStoreOnlyURLsAndCanBeRestored() async throws {
        try await MainActor.run {
            try withPasteboard { board in
                let directory = FileManager.default.temporaryDirectory.appendingPathComponent(UUID().uuidString)
                try FileManager.default.createDirectory(at: directory, withIntermediateDirectories: true)
                defer { try? FileManager.default.removeItem(at: directory) }
                let file = directory.appendingPathComponent("文件 example.txt")
                try Data("This content must not enter history".utf8).write(to: file)
                var payload: ClipboardPayload?
                let monitor = ClipboardMonitor(pasteboard: board) { payload = $0; _ = $1 }
                put([[.fileURL: Data(file.absoluteString.utf8)]], on: board)
                monitor.poll()
                let captured = try #require(payload)
                #expect(captured.kind == .file)
                #expect(captured.plainText == file.path)
                #expect(Set(captured.items[0].representations.keys) == [NSPasteboard.PasteboardType.fileURL.rawValue])
                try PasteService(pasteboard: board).write(captured)
                #expect(board.string(forType: .fileURL) == file.absoluteString)
            }
        }
    }

    @Test
    func testMissingFileDoesNotOverwriteClipboard() async {
        await MainActor.run {
            withPasteboard { board in
                put([[.string: Data("keep me".utf8)]], on: board)
                let missingURL = FileManager.default.temporaryDirectory.appendingPathComponent(UUID().uuidString)
                let payload = ClipboardPayload(items: [ClipboardPayloadItem(representations: [
                    NSPasteboard.PasteboardType.fileURL.rawValue: Data(missingURL.absoluteString.utf8)
                ])], plainText: missingURL.path, kind: .file)
                let previousCount = board.changeCount
                #expect(throws: (any Error).self) { try PasteService(pasteboard: board).write(payload) }
                #expect(board.changeCount == previousCount)
                #expect(board.string(forType: .string) == "keep me")
            }
        }
    }

    @Test
    func testCaptureRejectsOversizedPayload() async {
        await MainActor.run {
            withPasteboard { board in
                var captured = 0
                let monitor = ClipboardMonitor(pasteboard: board) { _, _ in captured += 1 }
                put([[.png: Data(repeating: 0, count: ClipboardMonitor.maximumCaptureBytes + 1)]], on: board)
                monitor.poll()
                #expect(captured == 0)
            }
        }
    }

    @Test
    func testPNGAndURLTypesAreRecognized() async {
        await MainActor.run {
            withPasteboard { board in
                var kinds: [ClipboardKind] = []
                let monitor = ClipboardMonitor(pasteboard: board) { kinds.append($0.kind); _ = $1 }
                put([[.png: Data([137, 80, 78, 71])]], on: board)
                monitor.poll()
                put([[.URL: Data("https://example.com/path".utf8)]], on: board)
                monitor.poll()
                put([[.string: Data("https://example.com".utf8)]], on: board)
                monitor.poll()
                #expect(kinds == [.image, .link, .link])
            }
        }
    }

    @Test
    func testPlainTextWriteDropsFormatting() async throws {
        try await MainActor.run {
            try withPasteboard { board in
                let payload = ClipboardPayload(items: [ClipboardPayloadItem(representations: [
                    NSPasteboard.PasteboardType.string.rawValue: Data("hello".utf8),
                    NSPasteboard.PasteboardType.html.rawValue: Data("<b>hello</b>".utf8)
                ])], plainText: "hello", kind: .richText)
                try PasteService(pasteboard: board).write(payload, plainTextOnly: true)
                #expect(board.string(forType: .string) == "hello")
                #expect(board.data(forType: .html) == nil)
            }
        }
    }

    @MainActor
    @Test
    func testPasteWithoutTargetStillCopiesWithoutSendingKeys() async {
        let board = NSPasteboard(name: NSPasteboard.Name("ElegantClipbar.tests.\(UUID().uuidString)"))
        defer { board.releaseGlobally() }
        let payload = ClipboardPayload(items: [ClipboardPayloadItem(representations: [
            NSPasteboard.PasteboardType.string.rawValue: Data("copy only".utf8)
        ])], plainText: "copy only", kind: .text)
        var didWrite = false
        let outcome = await PasteService(pasteboard: board).paste(payload, to: nil) { didWrite = true }
        guard case .copiedOnly = outcome else {
            Issue.record("Pasting without a target must only copy")
            return
        }
        #expect(didWrite)
        #expect(board.string(forType: .string) == "copy only")
    }
}
